kind: pipeline
type: kubernetes
name: default

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

steps:
- name: build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build --network=host -t k8s-registry.nanotrading.io/grafana/grafana .
  - docker push k8s-registry.nanotrading.io/grafana/grafana
