kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: docker:19
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/
  commands:
  - docker build --network=host -t k8s-registry.nanotrading.io/grafana/grafana .
  - docker push k8s-registry.nanotrading.io/grafana/grafana
